name: Analytics
version: "1.0"
dbt-cloud:
    project-id: 70471823397825
analysis-paths: ["analyses"]
profile: ticketmasterargodemo  # For dbt-Core. configure in ~/.dbt/profiles.yml
models:
    +transient: false
    stage:
      stage_db:
        +copy_grants: true
        +database: ticketmasterargodemo
        +schema: stage
        +materialized: table

      production:
        +copy_grants: true
        +database: ticketmasterargodemo
        +schema: production
        +materialized: table
