name: Analytics
version: "1.0"
dbt-cloud:
    project-id: 70471823397825
analysis-paths: ["analyses"]
profile: Analytics  # For dbt-Core. configure in ~/.dbt/profiles.yml
models:
    +transient: false
    ticketmaster-demo-argo:
      stage_db:
        +copy_grants: true
        +database: ticketmaster-demo-argo
        +schema: stage_db
        +materialized: table

      ticketmaster_db:
        +copy_grants: true
        +database: ticketmaster-demo-argo
        +schema: ticketmaster_db
        +materialized: table
